//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codigos
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://siat.impuestos.gob.bo/", ConfigurationName="Codigos.ServicioFacturacionCodigos")]
    public interface ServicioFacturacionCodigos
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<Codigos.verificarComunicacionResponse> verificarComunicacionAsync(Codigos.verificarComunicacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<Codigos.verificarNitResponse> verificarNitAsync(Codigos.verificarNit request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<Codigos.cuisMasivoResponse> cuisMasivoAsync(Codigos.cuisMasivo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<Codigos.cufdResponse> cufdAsync(Codigos.cufd request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<Codigos.notificaCertificadoRevocadoResponse> notificaCertificadoRevocadoAsync(Codigos.notificaCertificadoRevocado request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<Codigos.cuisResponse> cuisAsync(Codigos.cuis request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<Codigos.cufdMasivoResponse> cufdMasivoAsync(Codigos.cufdMasivo request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaComunicacion : modelDto
    {
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public mensajeServicio[] mensajesList
        {
            get
            {
                return this.mensajesListField;
            }
            set
            {
                this.mensajesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class mensajeServicio : modelDto
    {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified
        {
            get
            {
                return this.codigoFieldSpecified;
            }
            set
            {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCufdMasivo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCuis))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCufd))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCuisMasivo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaConfiguracion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaNotificaRevocado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaVerificarNit))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeServicio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaComunicacion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class modelDto : model
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(modelDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCufdMasivo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCuis))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCufd))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaCuisMasivo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaConfiguracion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaNotificaRevocado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaVerificarNit))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeServicio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaComunicacion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class model
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudListaCufdDto
    {
        
        private int codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private int codigoSucursalField;
        
        private string cuisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoPuntoVenta
        {
            get
            {
                return this.codigoPuntoVentaField;
            }
            set
            {
                this.codigoPuntoVentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified
        {
            get
            {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set
            {
                this.codigoPuntoVentaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cuis
        {
            get
            {
                return this.cuisField;
            }
            set
            {
                this.cuisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudCufdMasivo
    {
        
        private int codigoAmbienteField;
        
        private int codigoModalidadField;
        
        private string codigoSistemaField;
        
        private solicitudListaCufdDto[] datosSolicitudField;
        
        private long nitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente
        {
            get
            {
                return this.codigoAmbienteField;
            }
            set
            {
                this.codigoAmbienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoModalidad
        {
            get
            {
                return this.codigoModalidadField;
            }
            set
            {
                this.codigoModalidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoSistema
        {
            get
            {
                return this.codigoSistemaField;
            }
            set
            {
                this.codigoSistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datosSolicitud", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public solicitudListaCufdDto[] datosSolicitud
        {
            get
            {
                return this.datosSolicitudField;
            }
            set
            {
                this.datosSolicitudField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long nit
        {
            get
            {
                return this.nitField;
            }
            set
            {
                this.nitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudCuis
    {
        
        private int codigoAmbienteField;
        
        private int codigoModalidadField;
        
        private System.Nullable<int> codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private string codigoSistemaField;
        
        private int codigoSucursalField;
        
        private long nitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente
        {
            get
            {
                return this.codigoAmbienteField;
            }
            set
            {
                this.codigoAmbienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoModalidad
        {
            get
            {
                return this.codigoModalidadField;
            }
            set
            {
                this.codigoModalidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> codigoPuntoVenta
        {
            get
            {
                return this.codigoPuntoVentaField;
            }
            set
            {
                this.codigoPuntoVentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified
        {
            get
            {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set
            {
                this.codigoPuntoVentaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string codigoSistema
        {
            get
            {
                return this.codigoSistemaField;
            }
            set
            {
                this.codigoSistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int codigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long nit
        {
            get
            {
                return this.nitField;
            }
            set
            {
                this.nitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudNotifcaRevocado
    {
        
        private string certificadoField;
        
        private int codigoAmbienteField;
        
        private string codigoSistemaField;
        
        private int codigoSucursalField;
        
        private string cuisField;
        
        private System.Nullable<System.DateTime> fechaRevocacionField;
        
        private bool fechaRevocacionFieldSpecified;
        
        private long nitField;
        
        private string razonRevocacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string certificado
        {
            get
            {
                return this.certificadoField;
            }
            set
            {
                this.certificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoAmbiente
        {
            get
            {
                return this.codigoAmbienteField;
            }
            set
            {
                this.codigoAmbienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoSistema
        {
            get
            {
                return this.codigoSistemaField;
            }
            set
            {
                this.codigoSistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int codigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cuis
        {
            get
            {
                return this.cuisField;
            }
            set
            {
                this.cuisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> fechaRevocacion
        {
            get
            {
                return this.fechaRevocacionField;
            }
            set
            {
                this.fechaRevocacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRevocacionSpecified
        {
            get
            {
                return this.fechaRevocacionFieldSpecified;
            }
            set
            {
                this.fechaRevocacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long nit
        {
            get
            {
                return this.nitField;
            }
            set
            {
                this.nitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string razonRevocacion
        {
            get
            {
                return this.razonRevocacionField;
            }
            set
            {
                this.razonRevocacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudCufd
    {
        
        private int codigoAmbienteField;
        
        private int codigoModalidadField;
        
        private System.Nullable<int> codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private string codigoSistemaField;
        
        private int codigoSucursalField;
        
        private string cuisField;
        
        private long nitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente
        {
            get
            {
                return this.codigoAmbienteField;
            }
            set
            {
                this.codigoAmbienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoModalidad
        {
            get
            {
                return this.codigoModalidadField;
            }
            set
            {
                this.codigoModalidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> codigoPuntoVenta
        {
            get
            {
                return this.codigoPuntoVentaField;
            }
            set
            {
                this.codigoPuntoVentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified
        {
            get
            {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set
            {
                this.codigoPuntoVentaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string codigoSistema
        {
            get
            {
                return this.codigoSistemaField;
            }
            set
            {
                this.codigoSistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int codigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string cuis
        {
            get
            {
                return this.cuisField;
            }
            set
            {
                this.cuisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long nit
        {
            get
            {
                return this.nitField;
            }
            set
            {
                this.nitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudListaCuisDto
    {
        
        private int codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private int codigoSucursalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoPuntoVenta
        {
            get
            {
                return this.codigoPuntoVentaField;
            }
            set
            {
                this.codigoPuntoVentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified
        {
            get
            {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set
            {
                this.codigoPuntoVentaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudCuisMasivoSistemas
    {
        
        private int codigoAmbienteField;
        
        private int codigoModalidadField;
        
        private string codigoSistemaField;
        
        private solicitudListaCuisDto[] datosSolicitudField;
        
        private long nitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente
        {
            get
            {
                return this.codigoAmbienteField;
            }
            set
            {
                this.codigoAmbienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoModalidad
        {
            get
            {
                return this.codigoModalidadField;
            }
            set
            {
                this.codigoModalidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoSistema
        {
            get
            {
                return this.codigoSistemaField;
            }
            set
            {
                this.codigoSistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datosSolicitud", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public solicitudListaCuisDto[] datosSolicitud
        {
            get
            {
                return this.datosSolicitudField;
            }
            set
            {
                this.datosSolicitudField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long nit
        {
            get
            {
                return this.nitField;
            }
            set
            {
                this.nitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudVerificarNit
    {
        
        private int codigoAmbienteField;
        
        private int codigoModalidadField;
        
        private string codigoSistemaField;
        
        private int codigoSucursalField;
        
        private string cuisField;
        
        private long nitField;
        
        private long nitParaVerificacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente
        {
            get
            {
                return this.codigoAmbienteField;
            }
            set
            {
                this.codigoAmbienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoModalidad
        {
            get
            {
                return this.codigoModalidadField;
            }
            set
            {
                this.codigoModalidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoSistema
        {
            get
            {
                return this.codigoSistemaField;
            }
            set
            {
                this.codigoSistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int codigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cuis
        {
            get
            {
                return this.cuisField;
            }
            set
            {
                this.cuisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long nit
        {
            get
            {
                return this.nitField;
            }
            set
            {
                this.nitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long nitParaVerificacion
        {
            get
            {
                return this.nitParaVerificacionField;
            }
            set
            {
                this.nitParaVerificacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaListaRegistroCufdSoapDto
    {
        
        private string codigoField;
        
        private string codigoControlField;
        
        private int codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private int codigoSucursalField;
        
        private bool codigoSucursalFieldSpecified;
        
        private string cuisField;
        
        private string direccionField;
        
        private System.DateTime fechaVigenciaField;
        
        private bool fechaVigenciaFieldSpecified;
        
        private mensajeServicio[] mensajeServicioListField;
        
        private bool transaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoControl
        {
            get
            {
                return this.codigoControlField;
            }
            set
            {
                this.codigoControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int codigoPuntoVenta
        {
            get
            {
                return this.codigoPuntoVentaField;
            }
            set
            {
                this.codigoPuntoVentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified
        {
            get
            {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set
            {
                this.codigoPuntoVentaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int codigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSucursalSpecified
        {
            get
            {
                return this.codigoSucursalFieldSpecified;
            }
            set
            {
                this.codigoSucursalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cuis
        {
            get
            {
                return this.cuisField;
            }
            set
            {
                this.cuisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime fechaVigencia
        {
            get
            {
                return this.fechaVigenciaField;
            }
            set
            {
                this.fechaVigenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVigenciaSpecified
        {
            get
            {
                return this.fechaVigenciaFieldSpecified;
            }
            set
            {
                this.fechaVigenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajeServicioList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public mensajeServicio[] mensajeServicioList
        {
            get
            {
                return this.mensajeServicioListField;
            }
            set
            {
                this.mensajeServicioListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaListaRegistroCuisSoapDto
    {
        
        private string codigoField;
        
        private int codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private int codigoSucursalField;
        
        private bool codigoSucursalFieldSpecified;
        
        private System.DateTime fechaVigenciaField;
        
        private bool fechaVigenciaFieldSpecified;
        
        private mensajeServicio[] mensajeServicioListField;
        
        private bool transaccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoPuntoVenta
        {
            get
            {
                return this.codigoPuntoVentaField;
            }
            set
            {
                this.codigoPuntoVentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified
        {
            get
            {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set
            {
                this.codigoPuntoVentaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int codigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSucursalSpecified
        {
            get
            {
                return this.codigoSucursalFieldSpecified;
            }
            set
            {
                this.codigoSucursalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaVigencia
        {
            get
            {
                return this.fechaVigenciaField;
            }
            set
            {
                this.fechaVigenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVigenciaSpecified
        {
            get
            {
                return this.fechaVigenciaFieldSpecified;
            }
            set
            {
                this.fechaVigenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajeServicioList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public mensajeServicio[] mensajeServicioList
        {
            get
            {
                return this.mensajeServicioListField;
            }
            set
            {
                this.mensajeServicioListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaCufdMasivo : modelDto
    {
        
        private respuestaListaRegistroCufdSoapDto[] listaRespuestasCufdField;
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaRespuestasCufd", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public respuestaListaRegistroCufdSoapDto[] listaRespuestasCufd
        {
            get
            {
                return this.listaRespuestasCufdField;
            }
            set
            {
                this.listaRespuestasCufdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public mensajeServicio[] mensajesList
        {
            get
            {
                return this.mensajesListField;
            }
            set
            {
                this.mensajesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaCuis : modelDto
    {
        
        private string codigoField;
        
        private System.DateTime fechaVigenciaField;
        
        private bool fechaVigenciaFieldSpecified;
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaVigencia
        {
            get
            {
                return this.fechaVigenciaField;
            }
            set
            {
                this.fechaVigenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVigenciaSpecified
        {
            get
            {
                return this.fechaVigenciaFieldSpecified;
            }
            set
            {
                this.fechaVigenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public mensajeServicio[] mensajesList
        {
            get
            {
                return this.mensajesListField;
            }
            set
            {
                this.mensajesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaCufd : modelDto
    {
        
        private string codigoField;
        
        private string codigoControlField;
        
        private string direccionField;
        
        private System.DateTime fechaVigenciaField;
        
        private bool fechaVigenciaFieldSpecified;
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoControl
        {
            get
            {
                return this.codigoControlField;
            }
            set
            {
                this.codigoControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaVigencia
        {
            get
            {
                return this.fechaVigenciaField;
            }
            set
            {
                this.fechaVigenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVigenciaSpecified
        {
            get
            {
                return this.fechaVigenciaFieldSpecified;
            }
            set
            {
                this.fechaVigenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public mensajeServicio[] mensajesList
        {
            get
            {
                return this.mensajesListField;
            }
            set
            {
                this.mensajesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaCuisMasivo : modelDto
    {
        
        private respuestaListaRegistroCuisSoapDto[] listaRespuestasCuisField;
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaRespuestasCuis", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public respuestaListaRegistroCuisSoapDto[] listaRespuestasCuis
        {
            get
            {
                return this.listaRespuestasCuisField;
            }
            set
            {
                this.listaRespuestasCuisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public mensajeServicio[] mensajesList
        {
            get
            {
                return this.mensajesListField;
            }
            set
            {
                this.mensajesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaNotificaRevocado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaVerificarNit))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaConfiguracion : modelDto
    {
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public mensajeServicio[] mensajesList
        {
            get
            {
                return this.mensajesListField;
            }
            set
            {
                this.mensajesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaNotificaRevocado : respuestaConfiguracion
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaVerificarNit : respuestaConfiguracion
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarComunicacion", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarComunicacion
    {
        
        public verificarComunicacion()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarComunicacionResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarComunicacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Codigos.respuestaComunicacion RespuestaComunicacion;
        
        public verificarComunicacionResponse()
        {
        }
        
        public verificarComunicacionResponse(Codigos.respuestaComunicacion RespuestaComunicacion)
        {
            this.RespuestaComunicacion = RespuestaComunicacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarNit", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarNit
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Codigos.solicitudVerificarNit SolicitudVerificarNit;
        
        public verificarNit()
        {
        }
        
        public verificarNit(Codigos.solicitudVerificarNit SolicitudVerificarNit)
        {
            this.SolicitudVerificarNit = SolicitudVerificarNit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarNitResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarNitResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Codigos.respuestaVerificarNit RespuestaVerificarNit;
        
        public verificarNitResponse()
        {
        }
        
        public verificarNitResponse(Codigos.respuestaVerificarNit RespuestaVerificarNit)
        {
            this.RespuestaVerificarNit = RespuestaVerificarNit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cuisMasivo", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cuisMasivo
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Codigos.solicitudCuisMasivoSistemas SolicitudCuisMasivoSistemas;
        
        public cuisMasivo()
        {
        }
        
        public cuisMasivo(Codigos.solicitudCuisMasivoSistemas SolicitudCuisMasivoSistemas)
        {
            this.SolicitudCuisMasivoSistemas = SolicitudCuisMasivoSistemas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cuisMasivoResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cuisMasivoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Codigos.respuestaCuisMasivo RespuestaCuisMasivo;
        
        public cuisMasivoResponse()
        {
        }
        
        public cuisMasivoResponse(Codigos.respuestaCuisMasivo RespuestaCuisMasivo)
        {
            this.RespuestaCuisMasivo = RespuestaCuisMasivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cufd", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cufd
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Codigos.solicitudCufd SolicitudCufd;
        
        public cufd()
        {
        }
        
        public cufd(Codigos.solicitudCufd SolicitudCufd)
        {
            this.SolicitudCufd = SolicitudCufd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cufdResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cufdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Codigos.respuestaCufd RespuestaCufd;
        
        public cufdResponse()
        {
        }
        
        public cufdResponse(Codigos.respuestaCufd RespuestaCufd)
        {
            this.RespuestaCufd = RespuestaCufd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="notificaCertificadoRevocado", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class notificaCertificadoRevocado
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Codigos.solicitudNotifcaRevocado SolicitudNotificaRevocado;
        
        public notificaCertificadoRevocado()
        {
        }
        
        public notificaCertificadoRevocado(Codigos.solicitudNotifcaRevocado SolicitudNotificaRevocado)
        {
            this.SolicitudNotificaRevocado = SolicitudNotificaRevocado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="notificaCertificadoRevocadoResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class notificaCertificadoRevocadoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Codigos.respuestaNotificaRevocado RespuestaNotificaRevocado;
        
        public notificaCertificadoRevocadoResponse()
        {
        }
        
        public notificaCertificadoRevocadoResponse(Codigos.respuestaNotificaRevocado RespuestaNotificaRevocado)
        {
            this.RespuestaNotificaRevocado = RespuestaNotificaRevocado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cuis", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cuis
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Codigos.solicitudCuis SolicitudCuis;
        
        public cuis()
        {
        }
        
        public cuis(Codigos.solicitudCuis SolicitudCuis)
        {
            this.SolicitudCuis = SolicitudCuis;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cuisResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cuisResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Codigos.respuestaCuis RespuestaCuis;
        
        public cuisResponse()
        {
        }
        
        public cuisResponse(Codigos.respuestaCuis RespuestaCuis)
        {
            this.RespuestaCuis = RespuestaCuis;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cufdMasivo", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cufdMasivo
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Codigos.solicitudCufdMasivo SolicitudCufdMasivo;
        
        public cufdMasivo()
        {
        }
        
        public cufdMasivo(Codigos.solicitudCufdMasivo SolicitudCufdMasivo)
        {
            this.SolicitudCufdMasivo = SolicitudCufdMasivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cufdMasivoResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class cufdMasivoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Codigos.respuestaCufdMasivo RespuestaCufdMasivo;
        
        public cufdMasivoResponse()
        {
        }
        
        public cufdMasivoResponse(Codigos.respuestaCufdMasivo RespuestaCufdMasivo)
        {
            this.RespuestaCufdMasivo = RespuestaCufdMasivo;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ServicioFacturacionCodigosChannel : Codigos.ServicioFacturacionCodigos, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServicioFacturacionCodigosClient : System.ServiceModel.ClientBase<Codigos.ServicioFacturacionCodigos>, Codigos.ServicioFacturacionCodigos
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioFacturacionCodigosClient() : 
                base(ServicioFacturacionCodigosClient.GetDefaultBinding(), ServicioFacturacionCodigosClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServicioFacturacionCodigosPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionCodigosClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioFacturacionCodigosClient.GetBindingForEndpoint(endpointConfiguration), ServicioFacturacionCodigosClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionCodigosClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioFacturacionCodigosClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionCodigosClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioFacturacionCodigosClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturacionCodigosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Codigos.verificarComunicacionResponse> Codigos.ServicioFacturacionCodigos.verificarComunicacionAsync(Codigos.verificarComunicacion request)
        {
            return base.Channel.verificarComunicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Codigos.verificarComunicacionResponse> verificarComunicacionAsync()
        {
            Codigos.verificarComunicacion inValue = new Codigos.verificarComunicacion();
            return ((Codigos.ServicioFacturacionCodigos)(this)).verificarComunicacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Codigos.verificarNitResponse> Codigos.ServicioFacturacionCodigos.verificarNitAsync(Codigos.verificarNit request)
        {
            return base.Channel.verificarNitAsync(request);
        }
        
        public System.Threading.Tasks.Task<Codigos.verificarNitResponse> verificarNitAsync(Codigos.solicitudVerificarNit SolicitudVerificarNit)
        {
            Codigos.verificarNit inValue = new Codigos.verificarNit();
            inValue.SolicitudVerificarNit = SolicitudVerificarNit;
            return ((Codigos.ServicioFacturacionCodigos)(this)).verificarNitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Codigos.cuisMasivoResponse> Codigos.ServicioFacturacionCodigos.cuisMasivoAsync(Codigos.cuisMasivo request)
        {
            return base.Channel.cuisMasivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Codigos.cuisMasivoResponse> cuisMasivoAsync(Codigos.solicitudCuisMasivoSistemas SolicitudCuisMasivoSistemas)
        {
            Codigos.cuisMasivo inValue = new Codigos.cuisMasivo();
            inValue.SolicitudCuisMasivoSistemas = SolicitudCuisMasivoSistemas;
            return ((Codigos.ServicioFacturacionCodigos)(this)).cuisMasivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Codigos.cufdResponse> Codigos.ServicioFacturacionCodigos.cufdAsync(Codigos.cufd request)
        {
            return base.Channel.cufdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Codigos.cufdResponse> cufdAsync(Codigos.solicitudCufd SolicitudCufd)
        {
            Codigos.cufd inValue = new Codigos.cufd();
            inValue.SolicitudCufd = SolicitudCufd;
            return ((Codigos.ServicioFacturacionCodigos)(this)).cufdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Codigos.notificaCertificadoRevocadoResponse> Codigos.ServicioFacturacionCodigos.notificaCertificadoRevocadoAsync(Codigos.notificaCertificadoRevocado request)
        {
            return base.Channel.notificaCertificadoRevocadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Codigos.notificaCertificadoRevocadoResponse> notificaCertificadoRevocadoAsync(Codigos.solicitudNotifcaRevocado SolicitudNotificaRevocado)
        {
            Codigos.notificaCertificadoRevocado inValue = new Codigos.notificaCertificadoRevocado();
            inValue.SolicitudNotificaRevocado = SolicitudNotificaRevocado;
            return ((Codigos.ServicioFacturacionCodigos)(this)).notificaCertificadoRevocadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Codigos.cuisResponse> Codigos.ServicioFacturacionCodigos.cuisAsync(Codigos.cuis request)
        {
            return base.Channel.cuisAsync(request);
        }
        
        public System.Threading.Tasks.Task<Codigos.cuisResponse> cuisAsync(Codigos.solicitudCuis SolicitudCuis)
        {
            Codigos.cuis inValue = new Codigos.cuis();
            inValue.SolicitudCuis = SolicitudCuis;
            return ((Codigos.ServicioFacturacionCodigos)(this)).cuisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Codigos.cufdMasivoResponse> Codigos.ServicioFacturacionCodigos.cufdMasivoAsync(Codigos.cufdMasivo request)
        {
            return base.Channel.cufdMasivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Codigos.cufdMasivoResponse> cufdMasivoAsync(Codigos.solicitudCufdMasivo SolicitudCufdMasivo)
        {
            Codigos.cufdMasivo inValue = new Codigos.cufdMasivo();
            inValue.SolicitudCufdMasivo = SolicitudCufdMasivo;
            return ((Codigos.ServicioFacturacionCodigos)(this)).cufdMasivoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioFacturacionCodigosPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioFacturacionCodigosPort))
            {
                return new System.ServiceModel.EndpointAddress("https://pilotosiatservicios.impuestos.gob.bo/v2/FacturacionCodigos");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioFacturacionCodigosClient.GetBindingForEndpoint(EndpointConfiguration.ServicioFacturacionCodigosPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioFacturacionCodigosClient.GetEndpointAddress(EndpointConfiguration.ServicioFacturacionCodigosPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ServicioFacturacionCodigosPort,
        }
    }
}
