//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class facturaComputarizadaHospitalClinica {
    
    private facturaComputarizadaHospitalClinicaCabecera cabeceraField;
    
    private facturaComputarizadaHospitalClinicaDetalle[] detalleField;
    
    /// <remarks/>
    public facturaComputarizadaHospitalClinicaCabecera cabecera {
        get {
            return this.cabeceraField;
        }
        set {
            this.cabeceraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("detalle")]
    public facturaComputarizadaHospitalClinicaDetalle[] detalle {
        get {
            return this.detalleField;
        }
        set {
            this.detalleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class facturaComputarizadaHospitalClinicaCabecera {
    
    private string nitEmisorField;
    
    private string razonSocialEmisorField;
    
    private string municipioField;
    
    private string telefonoField;
    
    private string numeroFacturaField;
    
    private string cufField;
    
    private string cufdField;
    
    private string codigoSucursalField;
    
    private string direccionField;
    
    private string codigoPuntoVentaField;
    
    private System.DateTime fechaEmisionField;
    
    private string nombreRazonSocialField;
    
    private string codigoTipoDocumentoIdentidadField;
    
    private string numeroDocumentoField;
    
    private string complementoField;
    
    private string codigoClienteField;
    
    private string modalidadServicioField;
    
    private string codigoMetodoPagoField;
    
    private string numeroTarjetaField;
    
    private decimal montoTotalField;
    
    private decimal montoTotalSujetoIvaField;
    
    private string codigoMonedaField;
    
    private decimal tipoCambioField;
    
    private decimal montoTotalMonedaField;
    
    private System.Nullable<decimal> montoGiftCardField;
    
    private System.Nullable<decimal> descuentoAdicionalField;
    
    private string codigoExcepcionField;
    
    private string cafcField;
    
    private string leyendaField;
    
    private string usuarioField;
    
    private string codigoDocumentoSectorField;
    
    public facturaComputarizadaHospitalClinicaCabecera() {
        this.codigoDocumentoSectorField = "17";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string nitEmisor {
        get {
            return this.nitEmisorField;
        }
        set {
            this.nitEmisorField = value;
        }
    }
    
    /// <remarks/>
    public string razonSocialEmisor {
        get {
            return this.razonSocialEmisorField;
        }
        set {
            this.razonSocialEmisorField = value;
        }
    }
    
    /// <remarks/>
    public string municipio {
        get {
            return this.municipioField;
        }
        set {
            this.municipioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string telefono {
        get {
            return this.telefonoField;
        }
        set {
            this.telefonoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string numeroFactura {
        get {
            return this.numeroFacturaField;
        }
        set {
            this.numeroFacturaField = value;
        }
    }
    
    /// <remarks/>
    public string cuf {
        get {
            return this.cufField;
        }
        set {
            this.cufField = value;
        }
    }
    
    /// <remarks/>
    public string cufd {
        get {
            return this.cufdField;
        }
        set {
            this.cufdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codigoSucursal {
        get {
            return this.codigoSucursalField;
        }
        set {
            this.codigoSucursalField = value;
        }
    }
    
    /// <remarks/>
    public string direccion {
        get {
            return this.direccionField;
        }
        set {
            this.direccionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string codigoPuntoVenta {
        get {
            return this.codigoPuntoVentaField;
        }
        set {
            this.codigoPuntoVentaField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime fechaEmision {
        get {
            return this.fechaEmisionField;
        }
        set {
            this.fechaEmisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string nombreRazonSocial {
        get {
            return this.nombreRazonSocialField;
        }
        set {
            this.nombreRazonSocialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codigoTipoDocumentoIdentidad {
        get {
            return this.codigoTipoDocumentoIdentidadField;
        }
        set {
            this.codigoTipoDocumentoIdentidadField = value;
        }
    }
    
    /// <remarks/>
    public string numeroDocumento {
        get {
            return this.numeroDocumentoField;
        }
        set {
            this.numeroDocumentoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string complemento {
        get {
            return this.complementoField;
        }
        set {
            this.complementoField = value;
        }
    }
    
    /// <remarks/>
    public string codigoCliente {
        get {
            return this.codigoClienteField;
        }
        set {
            this.codigoClienteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string modalidadServicio {
        get {
            return this.modalidadServicioField;
        }
        set {
            this.modalidadServicioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codigoMetodoPago {
        get {
            return this.codigoMetodoPagoField;
        }
        set {
            this.codigoMetodoPagoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string numeroTarjeta {
        get {
            return this.numeroTarjetaField;
        }
        set {
            this.numeroTarjetaField = value;
        }
    }
    
    /// <remarks/>
    public decimal montoTotal {
        get {
            return this.montoTotalField;
        }
        set {
            this.montoTotalField = value;
        }
    }
    
    /// <remarks/>
    public decimal montoTotalSujetoIva {
        get {
            return this.montoTotalSujetoIvaField;
        }
        set {
            this.montoTotalSujetoIvaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codigoMoneda {
        get {
            return this.codigoMonedaField;
        }
        set {
            this.codigoMonedaField = value;
        }
    }
    
    /// <remarks/>
    public decimal tipoCambio {
        get {
            return this.tipoCambioField;
        }
        set {
            this.tipoCambioField = value;
        }
    }
    
    /// <remarks/>
    public decimal montoTotalMoneda {
        get {
            return this.montoTotalMonedaField;
        }
        set {
            this.montoTotalMonedaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> montoGiftCard {
        get {
            return this.montoGiftCardField;
        }
        set {
            this.montoGiftCardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> descuentoAdicional {
        get {
            return this.descuentoAdicionalField;
        }
        set {
            this.descuentoAdicionalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string codigoExcepcion {
        get {
            return this.codigoExcepcionField;
        }
        set {
            this.codigoExcepcionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string cafc {
        get {
            return this.cafcField;
        }
        set {
            this.cafcField = value;
        }
    }
    
    /// <remarks/>
    public string leyenda {
        get {
            return this.leyendaField;
        }
        set {
            this.leyendaField = value;
        }
    }
    
    /// <remarks/>
    public string usuario {
        get {
            return this.usuarioField;
        }
        set {
            this.usuarioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codigoDocumentoSector {
        get {
            return this.codigoDocumentoSectorField;
        }
        set {
            this.codigoDocumentoSectorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class facturaComputarizadaHospitalClinicaDetalle {
    
    private string actividadEconomicaField;
    
    private string codigoProductoSinField;
    
    private string codigoProductoField;
    
    private string descripcionField;
    
    private string especialidadField;
    
    private string especialidadDetalleField;
    
    private string nroQuirofanoSalaOperacionesField;
    
    private string especialidadMedicoField;
    
    private string nombreApellidoMedicoField;
    
    private string nitDocumentoMedicoField;
    
    private string nroMatriculaMedicoField;
    
    private string nroFacturaMedicoField;
    
    private decimal cantidadField;
    
    private string unidadMedidaField;
    
    private decimal precioUnitarioField;
    
    private System.Nullable<decimal> montoDescuentoField;
    
    private decimal subTotalField;
    
    /// <remarks/>
    public string actividadEconomica {
        get {
            return this.actividadEconomicaField;
        }
        set {
            this.actividadEconomicaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string codigoProductoSin {
        get {
            return this.codigoProductoSinField;
        }
        set {
            this.codigoProductoSinField = value;
        }
    }
    
    /// <remarks/>
    public string codigoProducto {
        get {
            return this.codigoProductoField;
        }
        set {
            this.codigoProductoField = value;
        }
    }
    
    /// <remarks/>
    public string descripcion {
        get {
            return this.descripcionField;
        }
        set {
            this.descripcionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string especialidad {
        get {
            return this.especialidadField;
        }
        set {
            this.especialidadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string especialidadDetalle {
        get {
            return this.especialidadDetalleField;
        }
        set {
            this.especialidadDetalleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string nroQuirofanoSalaOperaciones {
        get {
            return this.nroQuirofanoSalaOperacionesField;
        }
        set {
            this.nroQuirofanoSalaOperacionesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string especialidadMedico {
        get {
            return this.especialidadMedicoField;
        }
        set {
            this.especialidadMedicoField = value;
        }
    }
    
    /// <remarks/>
    public string nombreApellidoMedico {
        get {
            return this.nombreApellidoMedicoField;
        }
        set {
            this.nombreApellidoMedicoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string nitDocumentoMedico {
        get {
            return this.nitDocumentoMedicoField;
        }
        set {
            this.nitDocumentoMedicoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string nroMatriculaMedico {
        get {
            return this.nroMatriculaMedicoField;
        }
        set {
            this.nroMatriculaMedicoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string nroFacturaMedico {
        get {
            return this.nroFacturaMedicoField;
        }
        set {
            this.nroFacturaMedicoField = value;
        }
    }
    
    /// <remarks/>
    public decimal cantidad {
        get {
            return this.cantidadField;
        }
        set {
            this.cantidadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string unidadMedida {
        get {
            return this.unidadMedidaField;
        }
        set {
            this.unidadMedidaField = value;
        }
    }
    
    /// <remarks/>
    public decimal precioUnitario {
        get {
            return this.precioUnitarioField;
        }
        set {
            this.precioUnitarioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> montoDescuento {
        get {
            return this.montoDescuentoField;
        }
        set {
            this.montoDescuentoField = value;
        }
    }
    
    /// <remarks/>
    public decimal subTotal {
        get {
            return this.subTotalField;
        }
        set {
            this.subTotalField = value;
        }
    }
}
